use_frameworks!

target 'PODDIGIPROSDK_Example' do
  pod 'PODDIGIPROSDK', :path => '../'

  target 'PODDIGIPROSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
